version: '3.1'

networks:
    internal:
        driver: bridge

services:
    mysql:
        container_name: softexpert_mysql
        image: 'mysql:8.0'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=s3cr3t
            - MYSQL_DATABASE=softexpert
            - MYSQL_PASSWORD=s3cr3t
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
            - '3306:3306'
        networks:
            - internal

    server:
        image: webdevops/php-nginx-dev:8.2
        container_name: softexpert_server
        networks:
            - internal
        working_dir: /app
        volumes:
            - .:/app
            - ./.docker/nginx/custom.conf:/opt/docker/etc/nginx/vhost.common.d/custom.conf
            - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        depends_on:
            - mysql
        environment:
            - WEB_DOCUMENT_ROOT=/app/public
            - PHP_DISPLAY_ERRORS=0
            - PHP_MEMORY_LIMIT=2048M
            - PHP_MAX_EXECUTION_TIME=300
            - PHP_POST_MAX_SIZE=500M
            - PHP_UPLOAD_MAX_FILESIZE=500M
            - PHP_DEBUGGER="xdebug"
            - XDEBUG_MODE=debug
            - XDEBUG_START_WITH_REQUEST=yes
            - XDEBUG_CLIENT_HOST=host.docker.internal
            - XDEBUG_CLIENT_PORT=9090
            - XDEBUG_OUTPUT_DIR=/app/.xdebug
        expose:
            - 9090
        ports:
            - "80:80"

    app:
        container_name: softexpert_app
        image: node:16-alpine
        volumes:
            - ./resources/js:/app/resources/js
        working_dir: /app
        command: sh -c "cd /app/resources/js && yarn install && yarn run dev --host"
        ports:
            - '3000:3000'